require: rubocop-rspec

AllCops:
  DisplayStyleGuide: true
  Exclude:
    - db/schema.rb

### Layout rules


### Metric rules

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 60

Metrics/ClassLength:
  Max: 320

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 20

### Rails rules

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

### RSpec rules

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

### Style rules

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 3

Style/ClassAndModuleChildren:
  Enabled: false

Style/OptionalArguments:
  Enabled: false
