language: ruby
before_script:
  - bundle exec rake db:setup
jobs:
  include:
    - stage: rubocop
      script:
        - bundle exec rspec
    - stage: rspec
      script:
        - bundle exec rspec
